name: Sync Fork

on:  
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 4"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync and merge upstream repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: "https://github.com/dynamiclance/golang-interview-questions-and-answers-bangla" # Replace with actual upstream repository URL
          upstream_branch: "main"  # Adjust if different
          downstream_branch: "main"  # Adjust if needed
          token: ${{ secrets.GITHUB_TOKEN }}
       
