name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Ensures full history is fetched

      - name: Set up git remote for upstream
        run: |
          git remote add upstream https://github.com/dynamiclance/golang-interview-questions-and-answers-bangla.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main --no-edit
          git push origin main
